_commit: 0.2.4
_src_path: gl:banter-bus/fastapi-template
database_name: management_api
service_name: banter-bus-management-api
service_prefix: BANTER_BUS_MANAGEMENT_API
service_title: Banter Bus Management API
short_description: The management API used to manage game, question and stories for
  the Banter Bus application.
