image: python:3.9.8

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - pre
  - test

before_script:
  - pip install tox

publish-docker:test:
  stage: pre
  only:
    - main
  image: docker
  services:
    - docker:dind
  before_script: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:test .
    - docker push ${CI_REGISTRY_IMAGE}:test

test:lint:
  stage: test
  only:
    - merge_request
  script:
    - make lint

test:unit-tests:
  stage: test
  only:
    - merge_request
  script:
    - make unit_tests || true

test:coverage:
  stage: test
  only:
    - main
    - merge_request
  script:
    - make coverage || true
  coverage: '/^TOTAL.+?(\S+\%)$/'

test:integration-tests:
  stage: test
  only:
    - merge_request
  script:
    - make integration_tests || true
